# Generated by Django 5.2.4 on 2025-07-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_happiness_index_user_height_user_profession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='happiness_index',
        ),
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weight',
        ),
    ]
