# Generated by Django 5.2.3 on 2025-07-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(choices=[('home', 'Home')], max_length=100, unique=True)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='web/')),
                ('font', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
