# Generated by Django 5.2.3 on 2025-06-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo_hex', models.CharField(max_length=7, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
